#!/bin/bash

file="${1/#\~\//$HOME/}"
line="$2"

case "$file" in
  *.md|*.markdown)
    if command -v mdcat &>/dev/null; then
      mdcat --ansi "$file"
    else
      bat --color=always --style=header,grid --terminal-width=999 -H "$line" "$file"
    fi
    ;;
  *)
    bat --color=always --style=header,grid --terminal-width=999 -H "$line" "$file"
    ;;
esac
