#!/usr/bin/env bash

echo "" | fzf \
    --with-shell 'bash -c' \
    --height 100% \
    --layout reverse \
    --ansi \
    --no-preview \
    --info hidden \
    --prompt " " \
    --query "snitch ls" \
    --disabled \
    --header "$(snitch ls 2>/dev/null | sed -n '2p')" \
    --bind "start:reload:snitch ls 2>/dev/null | tail -n +4 | sed '\$d'" \
    --bind "change:reload:eval {q} 2>/dev/null | tail -n +4 | sed '\$d'" \
    --bind "ctrl-x:execute-silent(kill {2})+reload:eval {q} 2>/dev/null | tail -n +4 | sed '\$d'"

